// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://razqoyfwnkhcvrbtgyva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhenFveWZ3bmtoY3ZyYnRneXZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDg2NzQsImV4cCI6MjA3MDEyNDY3NH0.BJ78PyhK9fHFrFg7XdOGdOYKHOx0NvB2qOB8pFaTKec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});